export type MediaOpportunitySourceArea = "watch" | "opportunities" | "replays";

export type MediaOpportunitySourceScope = "cote-divoire" | "africa" | "international";

export type MediaOpportunitySourceFeedType = "rss" | "site" | "channel" | "internal";

export type MediaOpportunitySource = {
  id: string;
  area: MediaOpportunitySourceArea;
  scope: MediaOpportunitySourceScope;
  feedType: MediaOpportunitySourceFeedType;
  title: string;
  publisher: string;
  url: string;
  descriptionFr: string;
  descriptionEn: string;
  cadenceFr: string;
  cadenceEn: string;
};

export const mediaOpportunitySources: MediaOpportunitySource[] = [
  {
    id: "openai-news",
    area: "watch",
    scope: "international",
    feedType: "rss",
    title: "OpenAI News",
    publisher: "OpenAI",
    url: "https://openai.com/news/rss.xml",
    descriptionFr: "Flux officiel produits, recherche et annonces à reconditionner en capsules courtes et newsletter.",
    descriptionEn: "Official product, research and launch feed to repackage into short-form content and newsletter briefs.",
    cadenceFr: "quotidien / RSS",
    cadenceEn: "daily / RSS",
  },
  {
    id: "anthropic-news",
    area: "watch",
    scope: "international",
    feedType: "rss",
    title: "Anthropic Newsroom",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/news/rss.xml",
    descriptionFr: "Annonces Claude, sécurité, API et cas d'usage entreprise utiles pour la veille TransferAI.",
    descriptionEn: "Claude, safety, API and enterprise announcements useful for the TransferAI watch.",
    cadenceFr: "hebdomadaire / RSS",
    cadenceEn: "weekly / RSS",
  },
  {
    id: "google-research-blog",
    area: "watch",
    scope: "international",
    feedType: "rss",
    title: "Google Research Blog",
    publisher: "Google Research",
    url: "https://research.google/blog/rss/",
    descriptionFr: "Recherche appliquée, multimodal, santé, éducation et productivité à traduire en impacts métier.",
    descriptionEn: "Applied research, multimodal, health, education and productivity updates to translate into business impact.",
    cadenceFr: "hebdomadaire / RSS",
    cadenceEn: "weekly / RSS",
  },
  {
    id: "hugging-face-blog",
    area: "watch",
    scope: "international",
    feedType: "rss",
    title: "Hugging Face Blog",
    publisher: "Hugging Face",
    url: "https://huggingface.co/blog/feed.xml",
    descriptionFr: "Open source, agents, modèles et guides pratiques utiles pour produire des formats pédagogiques courts.",
    descriptionEn: "Open-source, agents, models and hands-on guides fit for short educational content.",
    cadenceFr: "continu / RSS",
    cadenceEn: "continuous / RSS",
  },
  {
    id: "meta-ai-blog",
    area: "watch",
    scope: "international",
    feedType: "site",
    title: "Meta AI Blog",
    publisher: "Meta",
    url: "https://ai.meta.com/blog/",
    descriptionFr: "Recherche Meta AI, infra, open models et publication de référence à scrapper par page.",
    descriptionEn: "Meta AI research, infra, open models and flagship posts to scrape from the web page.",
    cadenceFr: "continu / site",
    cadenceEn: "continuous / site",
  },
  {
    id: "deepmind-blog",
    area: "watch",
    scope: "international",
    feedType: "site",
    title: "Google DeepMind Blog",
    publisher: "Google DeepMind",
    url: "https://deepmind.google/discover/blog/",
    descriptionFr: "Percées recherche et produits utiles pour les replays, dossiers newsletter et comparatifs outils.",
    descriptionEn: "Research and product breakthroughs that feed replays, newsletter dossiers and tool comparisons.",
    cadenceFr: "continu / site",
    cadenceEn: "continuous / site",
  },
  {
    id: "microsoft-ai-blog",
    area: "watch",
    scope: "international",
    feedType: "site",
    title: "Microsoft AI Blog",
    publisher: "Microsoft",
    url: "https://blogs.microsoft.com/ai/",
    descriptionFr: "Cas d'usage Copilot, agents, productivité et gouvernance pour contenus orientés entreprises.",
    descriptionEn: "Copilot, agent, productivity and governance posts for company-focused content.",
    cadenceFr: "continu / site",
    cadenceEn: "continuous / site",
  },
  {
    id: "nvidia-ai-blog",
    area: "watch",
    scope: "international",
    feedType: "site",
    title: "NVIDIA AI Blog",
    publisher: "NVIDIA",
    url: "https://blogs.nvidia.com/blog/category/generative-ai/",
    descriptionFr: "IA générative, agents et infrastructure pour angles performance, coût et souveraineté technique.",
    descriptionEn: "Generative AI, agents and infrastructure for performance, cost and technical sovereignty angles.",
    cadenceFr: "continu / site",
    cadenceEn: "continuous / site",
  },
  {
    id: "emploi-ci-ai",
    area: "opportunities",
    scope: "cote-divoire",
    feedType: "site",
    title: "Emploi.ci IA",
    publisher: "Emploi.ci",
    url: "https://www.emploi.ci/emploi-intelligence-artificielle",
    descriptionFr: "Offres Côte d'Ivoire liées à l'intelligence artificielle, data et transformation digitale.",
    descriptionEn: "Côte d'Ivoire listings related to artificial intelligence, data and digital transformation.",
    cadenceFr: "à surveiller chaque semaine",
    cadenceEn: "review weekly",
  },
  {
    id: "jobivoire",
    area: "opportunities",
    scope: "cote-divoire",
    feedType: "site",
    title: "JobIvoire",
    publisher: "JobIvoire",
    url: "https://www.jobivoire.ci/",
    descriptionFr: "Plateforme locale utile pour détecter offres data, IA, support digital et profils hybrides.",
    descriptionEn: "Local platform useful to detect data, AI, digital support and hybrid-role openings.",
    cadenceFr: "à surveiller chaque semaine",
    cadenceEn: "review weekly",
  },
  {
    id: "jobexpress-ci",
    area: "opportunities",
    scope: "cote-divoire",
    feedType: "site",
    title: "JobExpress CI",
    publisher: "JobExpress",
    url: "https://jobexpress.ci/",
    descriptionFr: "Source complémentaire pour stage, emploi junior et fonctions support pouvant basculer vers l'IA.",
    descriptionEn: "Complementary source for internships, junior roles and support functions that can shift toward AI.",
    cadenceFr: "hebdomadaire",
    cadenceEn: "weekly",
  },
  {
    id: "emploistage-ci",
    area: "opportunities",
    scope: "cote-divoire",
    feedType: "site",
    title: "Emploi-Stage CI",
    publisher: "Emploi-Stage",
    url: "https://emploistage.ci/",
    descriptionFr: "Bon point d'entrée pour stages, alternances et premiers débouchés IA en Côte d'Ivoire.",
    descriptionEn: "Strong entry point for internships and early AI opportunities in Côte d'Ivoire.",
    cadenceFr: "hebdomadaire",
    cadenceEn: "weekly",
  },
  {
    id: "we-work-remotely-ai",
    area: "opportunities",
    scope: "international",
    feedType: "site",
    title: "We Work Remotely · AI Jobs",
    publisher: "We Work Remotely",
    url: "https://weworkremotely.com/remote-jobs-artificial-intelligence-ai",
    descriptionFr: "Veille internationale sur les rôles IA remote, utile pour benchmark salaires et compétences demandées.",
    descriptionEn: "International remote AI roles watch, useful for salary and skills benchmarking.",
    cadenceFr: "continu / site",
    cadenceEn: "continuous / site",
  },
  {
    id: "remote-ok-ai",
    area: "opportunities",
    scope: "international",
    feedType: "site",
    title: "Remote OK · AI Jobs",
    publisher: "Remote OK",
    url: "https://remoteok.com/remote-AI-jobs",
    descriptionFr: "Source rapide pour les missions et postes IA internationaux, surtout produit, data et automation.",
    descriptionEn: "Fast source for international AI roles and missions, especially product, data and automation.",
    cadenceFr: "continu / site",
    cadenceEn: "continuous / site",
  },
  {
    id: "transferai-webinars",
    area: "replays",
    scope: "africa",
    feedType: "internal",
    title: "Replays & webinaires TransferAI",
    publisher: "TransferAI Africa",
    url: "/seminaires",
    descriptionFr: "Point d'entrée interne pour valoriser les replays, lives à venir et renvoyer vers l'inscription.",
    descriptionEn: "Internal entry point to highlight replays, upcoming live sessions and registration paths.",
    cadenceFr: "mise à jour continue",
    cadenceEn: "continuous updates",
  },
  {
    id: "transferai-youtube",
    area: "replays",
    scope: "africa",
    feedType: "channel",
    title: "Chaîne YouTube TransferAI",
    publisher: "TransferAI Africa",
    url: "https://www.youtube.com/@transferai-africa",
    descriptionFr: "Canal à pousser pour les tutoriels, masterclass longues et extraits de replays.",
    descriptionEn: "Primary channel for tutorials, long-form masterclasses and replay highlights.",
    cadenceFr: "2 vidéos / semaine",
    cadenceEn: "2 videos / week",
  },
  {
    id: "transferai-tiktok",
    area: "replays",
    scope: "africa",
    feedType: "channel",
    title: "TikTok TransferAI",
    publisher: "TransferAI Africa",
    url: "https://www.tiktok.com/@transfer_ai_africa",
    descriptionFr: "Capsules courtes pour transformer la veille en acquisition, puis rediriger vers newsletter et site.",
    descriptionEn: "Short clips that turn the watch into audience acquisition, then route visitors to newsletter and site.",
    cadenceFr: "5 capsules / semaine",
    cadenceEn: "5 clips / week",
  },
];

export const watchSources = mediaOpportunitySources.filter((source) => source.area === "watch");

export const opportunitySources = mediaOpportunitySources.filter((source) => source.area === "opportunities");

export const replaySources = mediaOpportunitySources.filter((source) => source.area === "replays");
