-- Seed de test pour la prospection multi-prospects TransferAI.
-- Objectif : charger 15 prospects variés pour tester la V4 batch,
-- y compris les règles d'arrêt et les quotas.

insert into public.prospect_targets (
  prospect_id,
  organization_name,
  website,
  country,
  organization_type,
  sector_guess,
  decision_maker_name,
  target_email,
  custom_page_paths_csv,
  booking_link_45min,
  commercial_priority_default,
  research_scope,
  source_backend,
  source_label,
  raw_source_id,
  source_payload,
  status,
  paused,
  do_not_contact,
  outreach_attempt_count,
  last_response_status,
  last_sequence_result,
  stop_reason,
  niche_status,
  next_action_at,
  notes_internal
)
values
  (
    'seed-001',
    'Orange Côte d''Ivoire',
    'https://www.orange.ci',
    'Côte d''Ivoire',
    'entreprise privée',
    'télécommunications et services B2B',
    'Décideur à confirmer',
    'contact1@example.org',
    '/,/entreprises/,/services/,/a-propos/,/contact/',
    'https://calendly.com/transferai/45min',
    'tier1',
    'public_web_only',
    'supabase',
    'seed_batch_ci',
    'seed-001',
    '{"seed": true, "cohort": "ci-b2b", "note": "eligible prospect"}'::jsonb,
    'ready',
    false,
    false,
    0,
    null,
    null,
    null,
    'candidate',
    now() - interval '1 day',
    'Eligible - télécoms'
  ),
  (
    'seed-002',
    'NSIA Technologies',
    'https://www.nsia.com',
    'Côte d''Ivoire',
    'groupe privé',
    'assurance, finance et transformation digitale',
    'Décideur à confirmer',
    'contact2@example.org',
    '/,/solutions/,/a-propos/,/carrieres/,/contact/',
    'https://calendly.com/transferai/45min',
    'tier1',
    'public_web_only',
    'supabase',
    'seed_batch_ci',
    'seed-002',
    '{"seed": true, "cohort": "ci-b2b"}'::jsonb,
    'ready',
    false,
    false,
    0,
    null,
    null,
    null,
    'candidate',
    now() - interval '2 hours',
    'Eligible - finance'
  ),
  (
    'seed-003',
    'SIFCA Digital',
    'https://www.sifca.ci',
    'Côte d''Ivoire',
    'groupe industriel',
    'industrie et opérations terrain',
    'Décideur à confirmer',
    'contact3@example.org',
    '/,/a-propos/,/metiers/,/contact/,/actualites/',
    'https://calendly.com/transferai/45min',
    'tier1',
    'public_web_only',
    'supabase',
    'seed_batch_ci',
    'seed-003',
    '{"seed": true, "cohort": "ci-industry"}'::jsonb,
    'active',
    false,
    false,
    1,
    'pending',
    null,
    null,
    'candidate',
    now() - interval '6 hours',
    'Eligible - industrie'
  ),
  (
    'seed-004',
    'Ecobank Innovation Desk',
    'https://www.ecobank.com',
    'Côte d''Ivoire',
    'banque',
    'banque, conformité et expérience client',
    'Décideur à confirmer',
    'contact4@example.org',
    '/,/about/,/group/,/business/,/contact/',
    'https://calendly.com/transferai/45min',
    'tier1',
    'public_web_only',
    'supabase',
    'seed_batch_ci',
    'seed-004',
    '{"seed": true, "cohort": "ci-banking"}'::jsonb,
    'ready',
    false,
    false,
    0,
    null,
    null,
    null,
    'candidate',
    now() - interval '8 hours',
    'Eligible - banque'
  ),
  (
    'seed-005',
    'SODECI Services',
    'https://www.sodeci.ci',
    'Côte d''Ivoire',
    'entreprise de services',
    'services publics et relation client',
    'Décideur à confirmer',
    'contact5@example.org',
    '/,/a-propos/,/services/,/contact/,/carrieres/',
    'https://calendly.com/transferai/45min',
    'tier2',
    'public_web_only',
    'supabase',
    'seed_batch_ci',
    'seed-005',
    '{"seed": true, "cohort": "ci-utilities"}'::jsonb,
    'ready',
    false,
    false,
    0,
    null,
    null,
    null,
    'candidate',
    now() - interval '5 hours',
    'Eligible - utilities'
  ),
  (
    'seed-006',
    'CIPREL Opérations',
    'https://www.ciprel.ci',
    'Côte d''Ivoire',
    'industrie énergétique',
    'énergie et maintenance',
    'Décideur à confirmer',
    'contact6@example.org',
    '/,/a-propos/,/activites/,/contact/,/carrieres/',
    'https://calendly.com/transferai/45min',
    'tier1',
    'public_web_only',
    'supabase',
    'seed_batch_ci',
    'seed-006',
    '{"seed": true, "cohort": "ci-energy"}'::jsonb,
    'active',
    true,
    false,
    0,
    null,
    null,
    null,
    'candidate',
    now() - interval '3 hours',
    'Doit être bloqué par paused=true'
  ),
  (
    'seed-007',
    'BICICI Data Office',
    'https://www.bicici.com',
    'Côte d''Ivoire',
    'banque',
    'banque et data',
    'Décideur à confirmer',
    'contact7@example.org',
    '/,/a-propos/,/entreprises/,/contact/,/carrieres/',
    'https://calendly.com/transferai/45min',
    'tier1',
    'public_web_only',
    'supabase',
    'seed_batch_ci',
    'seed-007',
    '{"seed": true, "cohort": "ci-banking"}'::jsonb,
    'active',
    false,
    true,
    0,
    null,
    null,
    null,
    'candidate',
    now() - interval '4 hours',
    'Doit être bloqué par do_not_contact=true'
  ),
  (
    'seed-008',
    'CFAO Mobility Services',
    'https://www.cfao.com',
    'Côte d''Ivoire',
    'groupe privé',
    'distribution, mobilité et service client',
    'Décideur à confirmer',
    'contact8@example.org',
    '/,/about-us/,/businesses/,/contact/',
    'https://calendly.com/transferai/45min',
    'tier1',
    'public_web_only',
    'supabase',
    'seed_batch_ci',
    'seed-008',
    '{"seed": true, "cohort": "ci-distribution"}'::jsonb,
    'ready',
    false,
    false,
    3,
    'pending',
    null,
    null,
    'candidate',
    now() - interval '1 day',
    'Doit être bloqué par max attempts'
  ),
  (
    'seed-009',
    'Banque Atlantique Innovation',
    'https://www.banqueatlantique.net',
    'Côte d''Ivoire',
    'banque',
    'banque et innovation',
    'Décideur à confirmer',
    'contact9@example.org',
    '/,/a-propos/,/entreprises/,/contact/',
    'https://calendly.com/transferai/45min',
    'tier1',
    'public_web_only',
    'supabase',
    'seed_batch_ci',
    'seed-009',
    '{"seed": true, "cohort": "ci-banking"}'::jsonb,
    'active',
    false,
    false,
    1,
    'interested',
    null,
    null,
    'candidate',
    now() - interval '2 days',
    'Doit être bloqué car séquence déjà close'
  ),
  (
    'seed-010',
    'Port Autonome d''Abidjan Digital',
    'https://www.portabidjan.ci',
    'Côte d''Ivoire',
    'institution publique',
    'logistique et opérations',
    'Décideur à confirmer',
    'contact10@example.org',
    '/,/a-propos/,/services/,/contact/',
    'https://calendly.com/transferai/45min',
    'tier2',
    'public_web_only',
    'supabase',
    'seed_batch_ci',
    'seed-010',
    '{"seed": true, "cohort": "ci-public"}'::jsonb,
    'ready',
    false,
    false,
    1,
    'pending',
    'no_niche',
    null,
    'no_niche',
    now() - interval '1 day',
    'Doit être bloqué car niche non retenue'
  ),
  (
    'seed-011',
    'SOTRA Expérience Voyageur',
    'https://www.sotra.ci',
    'Côte d''Ivoire',
    'service public',
    'transport et service client',
    'Décideur à confirmer',
    'contact11@example.org',
    '/,/presentation/,/services/,/contact/',
    'https://calendly.com/transferai/45min',
    'tier2',
    'public_web_only',
    'supabase',
    'seed_batch_ci',
    'seed-011',
    '{"seed": true, "cohort": "ci-transport"}'::jsonb,
    'ready',
    false,
    false,
    0,
    null,
    null,
    null,
    'candidate',
    now() + interval '2 days',
    'Eligible mais next_action_at futur'
  ),
  (
    'seed-012',
    'AfDB Innovation Lab',
    'https://www.afdb.org',
    'Côte d''Ivoire',
    'institution internationale',
    'finance du développement et knowledge management',
    'Décideur à confirmer',
    'contact12@example.org',
    '/,/about-us/,/en/topics-and-sectors/,/contact-us/',
    'https://calendly.com/transferai/45min',
    'tier2',
    'public_web_only',
    'airtable',
    'seed_batch_ci',
    'seed-012',
    '{"seed": true, "cohort": "intl-finance"}'::jsonb,
    'ready',
    false,
    false,
    0,
    null,
    null,
    null,
    'candidate',
    now() - interval '2 hours',
    'Eligible - institution internationale'
  ),
  (
    'seed-013',
    'UNICEF Côte d''Ivoire Programs',
    'https://www.unicef.org',
    'Côte d''Ivoire',
    'organisation internationale',
    'éducation, santé et opérations de programme',
    'Décideur à confirmer',
    'contact13@example.org',
    '/,/fr/cote-divoire/,/what-we-do/,/contact-us/',
    'https://calendly.com/transferai/45min',
    'tier2',
    'public_web_only',
    'google_sheets',
    'seed_batch_ci',
    'seed-013',
    '{"seed": true, "cohort": "intl-programs"}'::jsonb,
    'ready',
    false,
    false,
    0,
    null,
    null,
    null,
    'candidate',
    now() - interval '7 hours',
    'Eligible - ONG internationale'
  ),
  (
    'seed-014',
    'CNPS Modernisation',
    'https://www.cnps.ci',
    'Côte d''Ivoire',
    'institution publique',
    'gestion administrative et relation usager',
    'Décideur à confirmer',
    'contact14@example.org',
    '/,/presentation/,/services/,/contact/',
    'https://calendly.com/transferai/45min',
    'tier2',
    'public_web_only',
    'supabase',
    'seed_batch_ci',
    'seed-014',
    '{"seed": true, "cohort": "ci-public"}'::jsonb,
    'closed',
    false,
    false,
    2,
    'not_interested',
    null,
    'not_interested',
    'closed',
    now() - interval '10 days',
    'Doit être exclu en amont car status closed'
  ),
  (
    'seed-015',
    'TotalEnergies Marketing CI',
    'https://www.totalenergies.ci',
    'Côte d''Ivoire',
    'entreprise privée',
    'énergie, réseau commercial et marketing',
    'Décideur à confirmer',
    'contact15@example.org',
    '/,/a-propos/,/nos-offres/,/contact/',
    'https://calendly.com/transferai/45min',
    'tier1',
    'public_web_only',
    'supabase',
    'seed_batch_ci',
    'seed-015',
    '{"seed": true, "cohort": "ci-energy"}'::jsonb,
    'ready',
    false,
    false,
    0,
    null,
    null,
    null,
    'candidate',
    now() - interval '9 hours',
    'Eligible - énergie et marketing'
  )
on conflict (prospect_id) do update
set
  organization_name = excluded.organization_name,
  website = excluded.website,
  country = excluded.country,
  organization_type = excluded.organization_type,
  sector_guess = excluded.sector_guess,
  decision_maker_name = excluded.decision_maker_name,
  target_email = excluded.target_email,
  custom_page_paths_csv = excluded.custom_page_paths_csv,
  booking_link_45min = excluded.booking_link_45min,
  commercial_priority_default = excluded.commercial_priority_default,
  research_scope = excluded.research_scope,
  source_backend = excluded.source_backend,
  source_label = excluded.source_label,
  raw_source_id = excluded.raw_source_id,
  source_payload = excluded.source_payload,
  status = excluded.status,
  paused = excluded.paused,
  do_not_contact = excluded.do_not_contact,
  outreach_attempt_count = excluded.outreach_attempt_count,
  last_response_status = excluded.last_response_status,
  last_sequence_result = excluded.last_sequence_result,
  stop_reason = excluded.stop_reason,
  niche_status = excluded.niche_status,
  next_action_at = excluded.next_action_at,
  notes_internal = excluded.notes_internal,
  updated_at = now();

insert into public.do_not_contact (
  prospect_id,
  channel,
  reason
)
values
  ('seed-007', 'email', 'Prospect marqué en opposition pour test batch'),
  ('seed-014', 'all', 'Prospect clos pour test batch')
on conflict (prospect_id, channel) do update
set
  reason = excluded.reason;
