insert into public.job_opportunities (
  slug,
  title,
  summary_fr,
  summary_en,
  market_key,
  source_name,
  source_url,
  apply_url,
  location_fr,
  location_en,
  work_mode,
  opportunity_type,
  compensation_label,
  published_at,
  is_featured,
  is_new_manual,
  status
)
values
(
  'ai-specialist-upwork-long-term-remote',
  'AI Specialist',
  'Mission freelance mondiale de plus de 30h par semaine, orientee conception, entrainement et deploiement de solutions IA et machine learning, avec potentiel d''evolution vers un contrat plus durable.',
  'Worldwide freelance role for more than 30 hours per week, focused on designing, training, and deploying AI and machine learning solutions, with potential to evolve into a longer-term engagement.',
  'international',
  'Upwork',
  'https://www.upwork.com/freelance-jobs/apply/Specialist_~022013268796739478222/',
  'https://www.upwork.com/freelance-jobs/apply/Specialist_~022013268796739478222/',
  'A distance - mondial',
  'Remote - worldwide',
  'remote',
  'freelance',
  '$15-$30/hour',
  '2026-04-17T08:00:00.000Z',
  true,
  true,
  'published'
),
(
  'ai-expert-long-term-workflows-agents',
  'AI Expert - Long Term Opportunity',
  'Mission long terme sur audit de processus, automatisation metier et deploiement d''agents IA connectes a des outils comme Make, n8n, Zapier, Airtable ou Slack.',
  'Long-term opportunity focused on process audits, business automation, and deployment of AI agents connected to tools such as Make, n8n, Zapier, Airtable, or Slack.',
  'international',
  'Upwork',
  'https://www.upwork.com/freelance-jobs/apply/Expert-Long-Term-Opportunity_~021955787603491282211/',
  'https://www.upwork.com/freelance-jobs/apply/Expert-Long-Term-Opportunity_~021955787603491282211/',
  'A distance - mondial',
  'Remote - worldwide',
  'remote',
  'freelance',
  null,
  '2026-04-17T09:00:00.000Z',
  true,
  true,
  'published'
),
(
  'ai-agent-creation-ecommerce',
  'AI Agent Creation for E-commerce',
  'Mission freelance orientee e-commerce pour concevoir des agents IA sur support client, recommandations produits, suivi de commandes et automatisations metier.',
  'Freelance e-commerce project to design AI agents for customer support, product recommendations, order tracking, and business automations.',
  'international',
  'Upwork',
  'https://www.upwork.com/freelance-jobs/apply/Agent-Creation_~022014062927052952383/',
  'https://www.upwork.com/freelance-jobs/apply/Agent-Creation_~022014062927052952383/',
  'A distance - mondial',
  'Remote - worldwide',
  'remote',
  'freelance',
  '$800 fixed',
  '2026-04-17T10:00:00.000Z',
  false,
  true,
  'published'
),
(
  'hyperiondev-ai-engineer-johannesburg',
  'AI Engineer - HyperionDev',
  'Poste axe sur des produits developpeur assistes par IA generative, avec base a Johannesburg et flexibilite hybride ou remote dans un contexte africain concret.',
  'Role focused on developer products powered by generative AI, with a Johannesburg base and hybrid or remote flexibility in a concrete African market context.',
  'africa',
  'Greenhouse / HyperionDev',
  'https://boards.greenhouse.io/embed/job_app?token=8017819002',
  'https://boards.greenhouse.io/embed/job_app?token=8017819002',
  'Johannesburg - hybride / remote',
  'Johannesburg - hybrid / remote',
  'hybrid',
  'job',
  null,
  '2026-04-12T09:00:00.000Z',
  false,
  false,
  'published'
)
on conflict (slug) do update
set
  title = excluded.title,
  summary_fr = excluded.summary_fr,
  summary_en = excluded.summary_en,
  market_key = excluded.market_key,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  apply_url = excluded.apply_url,
  location_fr = excluded.location_fr,
  location_en = excluded.location_en,
  work_mode = excluded.work_mode,
  opportunity_type = excluded.opportunity_type,
  compensation_label = excluded.compensation_label,
  published_at = excluded.published_at,
  is_featured = excluded.is_featured,
  is_new_manual = excluded.is_new_manual,
  status = excluded.status,
  updated_at = now();
