// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
export const supabaseUnavailableMessage =
  "Supabase n'est pas configure localement. Ajoutez VITE_SUPABASE_URL et VITE_SUPABASE_PUBLISHABLE_KEY dans votre fichier .env.";

const createUnavailableSupabaseClient = () => {
  const error = new Error(supabaseUnavailableMessage);
  const result = {
    data: null,
    error,
  };
  const queryBuilder: {
    select: (...args: unknown[]) => typeof queryBuilder;
    eq: (...args: unknown[]) => typeof queryBuilder;
    order: (...args: unknown[]) => typeof queryBuilder;
    then: (onFulfilled: (value: typeof result) => unknown) => Promise<unknown>;
  } = {
    select: () => queryBuilder,
    eq: () => queryBuilder,
    order: () => queryBuilder,
    then: (onFulfilled) => Promise.resolve(onFulfilled(result)),
  };

  return {
    rpc: async () => ({
      data: null,
      error,
    }),
    from: (..._args: unknown[]) => queryBuilder,
    functions: {
      invoke: async () => ({
        data: null,
        error,
      }),
    },
  };
};

const createMemoryStorage = () => {
  const store = new Map<string, string>();

  return {
    getItem: (key: string) => store.get(key) ?? null,
    setItem: (key: string, value: string) => {
      store.set(key, value);
    },
    removeItem: (key: string) => {
      store.delete(key);
    },
  };
};

const authStorage = (() => {
  if (typeof globalThis === "undefined") {
    return createMemoryStorage();
  }

  try {
    const candidate = globalThis.localStorage;
    if (
      candidate &&
      typeof candidate.getItem === "function" &&
      typeof candidate.setItem === "function" &&
      typeof candidate.removeItem === "function"
    ) {
      return candidate;
    }
  } catch {
    return createMemoryStorage();
  }

  return createMemoryStorage();
})();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: authStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createUnavailableSupabaseClient();
